def menu_op():
    print('===========================================================================')
    print('\t\t\tA T M    O P E R A T I O N')
    print('===========================================================================')
    print()
    print('\t\t 1. Press 1 for Balance check')
    print('\t\t 2. Press 2 for Withdraw')
    print('\t\t 3. Press 3 for Deposit')
    print('\t\t 4. Press 4 for Change pin')
    print('\t\t 5. Press 5 for exit')
    print()
    print('===========================================================================')