def menu_op():
    print('===========================================================================')
    print('\tA R I T H M E T I C     O P E R A T I O N')
    print('===========================================================================')
    print()
    print('\t\t 1. Press 1 for addition')
    print('\t\t 2. Press 2 for substraction')
    print('\t\t 3. Press 3 for multipication')
    print('\t\t 4. Press 4 for division')
    print('\t\t 5. Press 5 for modulo division')
    print('\t\t 6. Press 6 for exponination')
    print('\t\t 7. Press 7 for exit')
    print()
    print('===========================================================================')